---
- name: Set up iptables
  hosts: all
  become: yes

  tasks:

    - name: Install iptables tools
      apt: name={{ item }} state=present update_cache=yes
      with_items:
          - "iptables"
          - "iptables-persistent"
      register: packages
    - debug: var=packages.stdout_lines
    - name: set iptables
      copy:
        src: ../resources/iptables/etc/iptables.up.rules
        dest: /etc/iptables.test.rules
    - name: apply iptables
      shell: |
        iptables-restore < /etc/iptables.test.rules
        iptables-save > /etc/iptables.up.rules
