---
- name: docker
  hosts: all
  become: yes

  tasks:

    - name: Prepare docker install
      apt: name={{ item }} state=present update_cache=yes
      with_items:
           - apt-transport-https
           - ca-certificates

    - name: install python-pip
      easy_install: name=pip

    - name: install docker-py
      pip: name=docker-py version=1.2.3

    - name: register apt docker key
      apt_key:
        keyserver: p80.pool.sks-keyservers.net
        id: 58118E89F3A912897C070ADBF76221572C52609D

    - name: add docker repo
      apt_repository: repo='deb https://apt.dockerproject.org/repo debian-jessie main' state=present

    - name: Install docker packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
          - docker-engine

    - name: Stop docker service
      service:
        name: docker
        state: stopped

    - name: Setup docker daemon options
      lineinfile:
        dest: /etc/default/docker
        state: present
        regexp: '^DOCKER_OPTS'
        line: 'DOCKER_OPTS="--iptalbes=true"'

    - name: Set oev user properties
      shell: |
        usermod -a -G docker oev

    - name: Kill SSH
      shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
      async: 3
      poll: 2

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes
