---
- name: docker
  hosts: all

  tasks:

    - name: Prepare docker install
      apt: name={{ item }} state=present update_cache=yes
      with_items:
           - apt-transport-https
           - ca-certificates
      sudo: yes

    - name: install python-pip
      easy_install: name=pip
      sudo: yes

    - name: install docker-py
      pip: name=docker-py version=1.2.3
      sudo: yes

    - name: register apt docker key
      apt_key:
        keyserver: p80.pool.sks-keyservers.net
        id: 58118E89F3A912897C070ADBF76221572C52609D
      sudo: yes

    - name: add docker repo
      apt_repository: repo='deb https://apt.dockerproject.org/repo debian-wheezy main' state=present
      sudo: yes

    - name: Install docker packages
      apt: name={{ item }} state=present update_cache=yes
      with_items:
          - docker-engine
      sudo: yes

    - name: Stop docker service
      service:
        name: docker
        state: stopped
      sudo: yes

    - name: Set oev user properties
      shell: |
        usermod -a -G docker oev
      sudo: yes

    - name: Kill SSH
      shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
      async: 3
      poll: 2

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes
      sudo: yes
