---
- name: jenkins
  hosts: all

  tasks:

  # This is the Debian package repository of Jenkins to automate installation and upgrade. To use this repository, first add the key to your system:
  # wget -q -O - http://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
  - name: Add apt key to the system
    apt_key: url=http://pkg.jenkins.io/debian-stable/jenkins.io.key state=present
    become: yes

  # Then add the following entry in your /etc/apt/sources.list:
  # deb http://pkg.jenkins.io/debian-stable binary/
  - name: Add deb entry to /etc/apt/sources.list
    apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present
    become: yes

  # Update your local package index, then finally install Jenkins:
  # sudo apt-get update
  # sudo apt-get install jenkins
  - name: Install Jenkins
    apt: name=jenkins update_cache=yes
    become: yes
    register: installJenkins
  - debug: var=installJenkins
